server.port=8080

spring.datasource.url=jdbc:mariadb://192.168.56.30:3306/menos?useSSL=false
spring.datasource.username=menos_app
spring.datasource.password=menos123
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver